services:
  - type: worker
    name: invest-help-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python Bot.py
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEFAULT_BASE
        value: usd
      - key: BOT_TOKEN
        sync: false
      - key: COINGECKO_API_KEY
        sync: false